---
title: "spatial_join"
format: html
editor: visual
warning: FALSE
code-fold: true
---

Load packages

```{r}
pacman::p_load('tidyverse', 
               'sf', 
               'here',
               'janitor',
               'tmap', 
               'kableExtra',
               'patchwork',
               'ggthemes',
               'colorRamps',
               'stars',
               'terra')
```


Read Rast (calfire)

```{r}
rast_path <- here::here('data','ds1327', 'tiff', 'ds1327.tif')

gdb_path <- here::here('data','ds1327', 'ds1327.gdb')

habitat <- rast(gdb_path)
```

Read Landfire rast (removed 1/24)

```{r}
# rast_path <- here::here('data', 'LF2024_FBFM13_250_CONUS', 'Tif', 'LC24_F13_250.tif')

# landfire <- rast(rast_path)

```

```{r}
veg_type <- habitat

activeCat(veg_type, layer = 1) <- 'LIFEFORM'
```

Read GAP GDB

```{r}
secretive <- read_csv(here('data', 'secretive_marshbird.csv')) %>% 
  clean_names() %>% 
  st_as_sf(coords = c("decimal_longitude", "decimal_latitude"), crs = 4326) %>% 
  st_transform(st_crs(veg_type))

```

```{r}
gap <- st_read(here::here('data',
                          'PADUS4_1_State_CA_GDB_KMZ', 
                          'PADUS4_1_StateCA.gdb'), 
                          quiet = TRUE) %>% 
  clean_names() 

gap_clean <- gap %>% 
  select(own_type, gap_sts, mang_type, Shape) %>% 
  st_transform(crs(veg_type)) %>%  # transform first
  st_cast("MULTIPOLYGON", warn = FALSE) %>%  # convert curves
  st_make_valid() %>%  # then fix validity
  group_by(gap_sts) %>%
  summarise(geometry = st_union(Shape), 
            .groups = 'drop')
```

Crop landfire to CA (removed 1/24)

```{r}
#landfire_CA <- crop(landfire, gap_clean)

```

Read Point Count

```{r}
point_count <- read_csv(here::here('data', 'point_count.csv')) %>% 
  clean_names()
```

Read area search

```{r}
area_search <- read_csv(here::here('data', 'area_search.csv')) %>% 
  clean_names()
```

Join both and make Geodatabase

```{r}
point_area_geo <- full_join(area_search, point_count) %>% 
  st_as_sf(coords = c("decimal_longitude", "decimal_latitude"), crs = 4326) %>% 
  st_transform(st_crs(veg_type))
```

Join with GAP

```{r}
birds_joined <- st_join(point_area_geo, gap_clean["gap_sts"])

```

Summary of by gap type

```{r}
birds_gap_sum <- birds_joined %>% 
  group_by(gap_sts) %>% 
  summarize(sum(observation_count, na.rm = TRUE))
```

merge everything we need

```{r}
veg_id <- terra::extract(veg_type, vect(birds_joined), ID = FALSE)[,1]

birds_joined$veg_type <- veg_id

birds_joined$gap_sts[is.na(birds_joined$gap_sts)] <- 5

```

Landfire join

```{r}
#land_id <- terra::extract(landfire_CA, vect(birds_joined), ID = FALSE)[,1]

#birds_joined$land_type <- land_id

#birds_joined$gap_sts[is.na(birds_joined$gap_sts)] <- 5
```

summary of gap status and veg_type

```{r}
birds_sum <- birds_joined %>% 
  group_by(gap_sts, veg_type) %>% 
  summarize(observations = sum(observation_count, na.rm = TRUE)) %>% 
 arrange(desc(observations)) 

birds_sum %>% 
  kable(format = "html", digits = 3,
      caption = "Observations, vegitation type, and gap status") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position   = "center",
    font_size  = 14
  ) %>% 
  row_spec(0, bold = TRUE, color = "white", background = "#A0185A") %>%  # header
  row_spec(1:nrow(birds_sum), color = "black", background = "#FFC4EB")
```

```{r}
plot(veg_type)
plot(vect(birds_sum), add = TRUE)
```

```{r}
crs(gap_clean) == crs(point_area_geo)
crs(point_area_geo) == crs(veg_type)


tm_shape(gap_clean)+
  tm_polygons(fill = "gap_sts",
              fill.legend = tm_legend(title = "GAP Status"),
              fill.scale = tm_scale(values = c('green',
                                               'yellow',
                                               '#ED7D3A',
                                               '#D33F49'),
                                    group = 'GAP Status'))+
tm_shape(point_area_geo)+
  tm_dots()
```


```{r}
tm_shape(veg_type)+
  tm_raster()+
tm_shape(point_area_geo)+
  tm_dots()
```




```{r}
birds_sum %>% 
  ggplot(aes(y = observations, x = gap_sts, group=gap_sts)) +
   geom_col(aes(fill = gap_sts),position = 'dodge')+
  facet_wrap(~veg_type)+
  coord_flip()
```
